# Usa a imagem oficial do Python 3.12 como base
FROM python:3.12

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas o arquivo de dependências para otimizar o cache do Docker
COPY requirements.txt .

# Atualiza o pip e instala as dependências
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copia o restante do código para o container
COPY scripts/ ./scripts/
COPY utils/ ./utils/
COPY main.py ./

# Cria os diretórios necessários para armazenar os arquivos JSON e XLSX
RUN mkdir -p /app/data/json /app/data/xlsx

# Define um volume para persistir os arquivos JSON/XLSX no host
VOLUME ["/app/data"]

# Garante que os diretórios existem antes de rodar o script
CMD ["/bin/sh", "-c", "mkdir -p /app/data/json /app/data/xlsx && python main.py"]
