FROM python:3.12

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y && apt-get clean

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/data/json /app/data/xlsx

VOLUME ["/app/data"]

CMD ["python", "main.py"]

### COMMANDS
# DOCKER BUID: docker build -t webscrap-tjsp .
# DOCKER RUN: docker run --rm -it -v "$(pwd)/data:/app/data" webscrap-tjsp
# DOCKER RUN ACESSO BASH: docker run --rm -it -v "$(pwd)/data:/app/data" --entrypoint /bin/bash webscrap-tjsp
